# Create paths here.
pages:
  # Example
  # - path: ''
  #   settings:
  #     controller: ''
  #     view: ''
  #     title: ''
  #     body_classes: ''
  #     access_role: ''

  - path: '/'
    settings:
      controller: 'HomeController'
      view: 'home'
      title: 'Home'
      body_classes: 'front-page home-page'
      access_role: 'guest'

  - path: '/login'
    settings:
      controller: 'LoginController'
      view: 'login'
      title: 'Login'
      body_classes: 'login-page'
      access_role: 'guest'

  - path: '/logout'
    settings:
      controller: 'LogoutController'
      view: 'logout'
      access_role: 'auth'

  - path: '/dashboard'
    settings:
      controller: 'DashboardController'
      view: 'dashboard'
      title: 'Dashboard'
      body_classes: 'dashboard-page'
      access_role: 'auth'

# Error pages.
pages.error:
  404:
    settings:
      controller: 'Error404Controller'
      view: 'error404'
      title: '404 - Page not found'
      body_classes: '404-page'
      access_role: 'guest'