# Create paths here.
pages:
  # Example
  # - path: ''
  #   settings:
  #     controller: ''
  #     view: ''
  #     title: ''
  #     body_classes: ''
  #     access_role: ''
  #   methods:
  #     get: ''
  #     post: ''

  - path: '/'
    settings:
      controller: 'HomeController'
      view: 'home'
      title: 'Home'
      body_classes: 'front-page home-page'
      access_role: 'guest'
    methods:
      get: 'index'

  - path: '/login'
    settings:
      controller: 'LoginController'
      view: 'login'
      title: 'Login'
      body_classes: 'login-page'
      access_role: 'guest'
    methods:
      get: 'index'
      post: 'login'

  - path: '/logout'
    settings:
      controller: 'LogoutController'
      view: 'logout'
      access_role: 'auth'
    methods:
      get: 'destroy'

  - path: '/register'
    settings:
      controller: 'RegisterController'
      view: 'register'
      title: 'Register'
      body_classes: 'register-page'
      access_role: 'guest'
    methods:
      get: 'index'
      post: 'store'

  - path: '/dashboard'
    settings:
      controller: 'DashboardController'
      view: 'dashboard'
      title: 'Dashboard'
      body_classes: 'dashboard-page'
      access_role: 'auth'
    methods:
      get: 'index'

  - path: '/users'
    settings:
      controller: 'UsersController'
      view: 'users'
      title: 'Users'
      body_classes: 'users-page'
      access_role: 'auth'
    methods:
      get: 'index'

  - path: '/users/create'
    settings:
      controller: 'UserController'
      view: 'users/create'
      title: 'Create user'
      body_classes: 'users-create-page'
      access_role: 'auth'
    methods:
      get: 'index'
      post: 'create'

  - path: '/users/:id'
    settings:
      controller: 'UserController'
      view: 'users/view'
      title: 'View user'
      body_classes: 'user-view-page'
      access_role: 'auth'
    methods:
      get: 'index'

  - path: '/users/:id/edit'
    settings:
      controller: 'UserController'
      view: 'users/edit'
      title: 'Edit user'
      body_classes: 'user-edit-page'
      access_role: 'auth'
    methods:
      get: 'index'
      post: 'edit'

  - path: '/users/:id/delete'
    settings:
      controller: 'UserController'
      view: 'users/delete'
      title: 'Delete user'
      body_classes: 'user-delete-page'
      access_role: 'auth'
    methods:
      get: 'index'
      post: 'delete'

# Error pages.
pages.error:
  404:
    settings:
      controller: 'Error404Controller'
      view: 'error404'
      title: '404 - Page not found'
      body_classes: '404-page'
      access_role: 'guest'
    methods:
      get: 'index'
